package com.main.nexus.model.enums;

public enum CompanyRejectionReason {
    MISSING_REQUIRED_SKILLS,
    INSUFFICIENT_EXPERIENCE,
    OVERQUALIFIED,
    TECHNOLOGY_MISMATCH,
    ROLE_EXPECTATION_MISMATCH,
    INCOMPLETE_PROFILE,
    POOR_QUALITY_PORTFOLIO,
    NO_RELEVANT_PROJECTS,
    FAILED_INTERVIEW_STAGE,
    NO_RESPONSE_FROM_CANDIDATE,
    ANOTHER_CANDIDATE_SELECTED,
    POSITION_FILLED,
    DEADLINE_TOO_SHORT,
    COST_BENEFIT_INADEQUATE,
    OTHER
}