package com.main.nexus.model.enums;

public enum ProfessionalRejectionReason {
    TOO_LOW_BUDGET,
    UNDESIRED_TECHNOLOGY,
    DISTANCE_TOO_LARGE,
    NO_REMOTE_OPTION,
    RELOCATION_NOT_ACCEPTED,
    TIMEZONE_INCOMPATIBILITY,
    NOT_AVAILABLE_TIMELINE,
    IMMEDIATE_START_REQUIRED,
    CANNOT_MEET_SCHEDULE,
    CULTURE_MISMATCH,
    COMPANY_SIZE_PREFERENCE,
    WORK_MODEL_MISMATCH,
    DEADLINE_TOO_SHORT,
    COST_BENEFIT_INADEQUATE,
    HIRING_FROZEN,
    PROJECT_CANCELLED,
    OTHER
}